### ISSUE TITLE
log map diverges around theta = Pi

### ISSUE THREAD

**Issue by nurlanov-zh** [jlblancoc/tutorial-se3-manifold#13]
The formula (9.16) for logarithm map (matrix -> vector-angle) needs to be corrected for the case when angle of rotation equals to or close to Pi.
See e.g. formulas (25, 26) [here](http://scipp.ucsc.edu/~haber/ph116A/rotation_11.pdf)

**Comment by nurlanov-zh** [comment]
Same issue with the Jacobian of logarithm.

**Comment by jlblancoc** [comment]
Hopefully fully fixed with PR #15 . Thanks!
