### ISSUE TITLE
some questions about formula in 10.3.9

### ISSUE THREAD

**Issue by gblack007** [jlblancoc/tutorial-se3-manifold#3]
hello, thanks for your work, but I have some doubts about the last jacobian formula in 10.3.9:
1. tAB should be tAD?
2. the last R(AD) should be R(A)?
is that so?

**Comment by jlblancoc** [comment]
Hi, 
Correct, thanks for the pointing it out! 
Fixed in 4d06dcfd43275b44a642c036de42eb0b3adb46fd and updated the online version of the PDF.
