### ISSUE TITLE
Question about Formulation 10.25

### ISSUE THREAD

**Issue by sqn175** [jlblancoc/tutorial-se3-manifold#8]
Hi, many thanks for the work! And I have a question about the formula 10.25 (report version: Technical report #012010 Last update: 29/05/2018) : 

[p_x, p_y, p_z]^T should be coordinates of (\mathbf p - \mathbf d_t) instead of  \mathbf p?  :)

**Comment by sqn175** [comment]
The report is correct, [p_x, p_y, p_z]^T is the coordinate of \mathbf p. 
The \mathbf d_t is eliminated using block matrix multiplication:

![image](https://user-images.githubusercontent.com/10163611/41139602-36e388ce-6b1b-11e8-86ed-071fd690eccd.png)

Note that the formula is simplified via representing the 3*3 right-corner block of Jacobian in Eqn. 10.25 by $\mathbf R_D^T \hat p$:
![image](https://user-images.githubusercontent.com/10163611/41139758-44a7855e-6b1c-11e8-9c97-ac1f57f0b9ff.png)

**Comment by jlblancoc** [comment]
Good you double-verified it!

Feel free of sending any further comment, or pull-requests with proposals for clarifications, etc.

Cheers.
