### ISSUE TITLE
Notation for hat operator

### ISSUE THREAD

**Issue by jbriales** [jlblancoc/tutorial-se3-manifold#9]
Hi JL!
I just saw the hat/vee operator notation you introduced a few months ago.
I was wondering in which context have you seen this exact notation, just to know how widespread it is.
Otherwise, personally I would rather favor the use of a Wedge (∧) placed as a superindex. As advantanges, this looks more consistent with the vee operator symbol and position, and is also more consistent with many other matrix operators (transpose, inverse, etc.)

What do you think about this?

**Comment by jlblancoc** [comment]
I agree with you! I was already uncomfortable with the lack of readability of the hat placement in some expressions. About the name "hat", I can't recall in how many places it's used, but for example it's named like that in "Sophus", etc. so I'll leave the name, but I have moved it as a superindex as you suggested.

The latest PDF version:  [here](http://ingmec.ual.es/~jlblanco/papers/jlblanco2010geometry3D_techrep.pdf).

**Comment by jlblancoc** [comment]
> As you say, it's used in Sophus and that seems a strong enough reference to take it as convention :)

Sure! Ask to the guys around you ;-)

> Btw, there is one minor error yet: After eq (7.5), 'hat' and 'vee' are applied in the wrong order ;)

Sure...fixed, thanks!
